name: Node.js CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Especifica la versión de Node.js que deseas usar

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
